Css canvas medical
hnguy96/c0321-code-solutions pull request #25
Opened 2021-03-16 16:58 UTC by hnguy96

![Screen Shot 2021-03-16 at 9 52 25 AM](https://user-images.githubusercontent.com/59902729/111348521-835d7800-863d-11eb-9a0e-07124f5b59f3.png)
![Screen Shot 2021-03-16 at 9 52 17 AM](https://user-images.githubusercontent.com/59902729/111348532-86586880-863d-11eb-8a05-474835ecc0d4.png)
![Screen Shot 2021-03-16 at 9 51 54 AM](https://user-images.githubusercontent.com/59902729/111348577-92dcc100-863d-11eb-9a4e-716c801e83ad.png)
![Screen Shot 2021-03-16 at 9 52 33 AM](https://user-images.githubusercontent.com/59902729/111348627-9bcd9280-863d-11eb-8e48-cc2247680985.png)
![Screen Shot 2021-03-16 at 9 56 15 AM](https://user-images.githubusercontent.com/59902729/111348887-e0592e00-863d-11eb-9532-78d6520bca9b.png)
![Screen Shot 2021-03-16 at 9 57 00 AM](https://user-images.githubusercontent.com/59902729/111349039-054da100-863e-11eb-8b5e-bd5de0285fd4.png)
![Screen Shot 2021-03-16 at 9 52 54 AM](https://user-images.githubusercontent.com/59902729/111348659-a0924680-863d-11eb-8d3d-dce249e86641.png)
![Screen Shot 2021-03-16 at 9 57 43 AM](https://user-images.githubusercontent.com/59902729/111349192-244c3300-863e-11eb-94d4-3edb79e131a9.png)
![Screen Shot 2021-03-16 at 9 58 00 AM](https://user-images.githubusercontent.com/59902729/111349211-27dfba00-863e-11eb-8f90-0a8acc2be02f.png)
![Screen Shot 2021-03-16 at 9 58 06 AM](https://user-images.githubusercontent.com/59902729/111349213-2910e700-863e-11eb-8bc2-2d8e7ff7317c.png)

2021-03-16 19:09 UTC, codingcodymiller requested changes
Hey Hien! The text in the header and footer "Canvas" is actually an image we've provided in the `images` folder, not text 😁 . Please use those images and submit again with a new screenshot, and I will take another look!

2021-03-16 20:00 UTC, hnguy96 commented
![Screen Shot 2021-03-16 at 12 59 58 PM](https://user-images.githubusercontent.com/59902729/111372221-98df9b80-8657-11eb-8ad3-0ec08d8b61e9.png)
![Screen Shot 2021-03-16 at 12 59 36 PM](https://user-images.githubusercontent.com/59902729/111372239-9d0bb900-8657-11eb-9709-752267e20703.png)

2021-03-16 22:24 UTC, codingcodymiller requested changes
Very nice work!! One more minor change:

2021-03-16 22:24 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +  max-width: 600px;
Whoops, duplicated property here! The one being used is the bottom one, so you can remove the top one.

2021-03-17 02:39 UTC, hnguy96 commented
![Screen Shot 2021-03-16 at 7 38 39 PM](https://user-images.githubusercontent.com/59902729/111406289-3efac800-868f-11eb-8085-7d8a72b15b3d.png)

Removed duplicated property in the `.location-heading` class because I realized it had no reason being there.

2021-03-17 15:50 UTC, codingcodymiller approved these changes
Nice work!!! 🥳 🥳 🥳

2021-03-17 22:40 UTC, merged