completed javascript loops
hnguy96/c0321-code-solutions pull request #31
Opened 2021-03-18 05:45 UTC by hnguy96

![Screen Shot 2021-03-17 at 10 37 13 PM](https://user-images.githubusercontent.com/59902729/111578992-61b1dd00-8772-11eb-8af6-2d87be4d7e63.png)

2021-03-18 19:58 UTC, codingcodymiller requested changes
Nice work!! One minor note to address:

2021-03-18 19:58 UTC, codingcodymiller commented on javascript-loops/main.js
> +    doubled.push(numbers[i] * numbers[i]);
This is squared, not doubled

2021-03-18 23:37 UTC, hnguy96 commented
![Screen Shot 2021-03-18 at 4 34 23 PM](https://user-images.githubusercontent.com/59902729/111711106-42fe2580-8808-11eb-93c0-a51806897b37.png)

2021-03-19 16:56 UTC, codingcodymiller approved these changes

2021-03-19 17:11 UTC, merged