Javascript typing tutor
hnguy96/c0321-code-solutions pull request #55
Opened 2021-03-30 16:41 UTC by hnguy96

![Screen Shot 2021-03-30 at 9 40 02 AM](https://user-images.githubusercontent.com/59902729/113024787-00a7e300-913c-11eb-8db9-d4bb16a8c3c1.png)
![Screen Shot 2021-03-30 at 9 39 37 AM](https://user-images.githubusercontent.com/59902729/113024794-0271a680-913c-11eb-94c2-2b07372a0679.png)

2021-04-05 18:31 UTC, codingcodymiller requested changes
Great start!! Please see my notes

2021-04-05 18:31 UTC, codingcodymiller commented on javascript-typing-tutor/main.js
> +      }
Both of these conditions are exactly the same 🤔 . You can probably refactor this to just one condition in just one conditional.

2021-04-06 15:28 UTC, hnguy96 commented
<img width="880" alt="Screen Shot 2021-04-06 at 8 25 48 AM" src="https://user-images.githubusercontent.com/59902729/113736479-fc3a7780-96b1-11eb-8a18-92249007ad40.png">

2021-04-06 16:52 UTC, codingcodymiller approved these changes

2021-04-06 16:53 UTC, merged